### ISSUE TITLE
Is imputation happening? Can we remove impute_missing_values()?

### ISSUE THREAD

**Issue by audreyrenson** [audreyrenson/nychanes2microbiome#2]
https://github.com/audreyrenson/nychanes2microbiome/blob/351352c4eeaed5cd5ba9be97e175ab92727af01c/R/utils.R#L311-L330

**Comment by lwaldron** [comment]
Agreed, there should be no imputation.

**Comment by lwaldron** [comment]
This issue was moved to waldronlab/nychanesmicrobiome#2
